name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.7

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v -o dist/node-versions .